In [9]:
import pandas as pd
import numpy as np

In [10]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]], columns=['cgpa', 'score', 'placed'])

In [11]:
df.head(4)

cgpa  score  placed
0     8      8       1
1     7      9       1
2     6     10       0
3     5     12       0

In [12]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [13]:
model= Sequential()
model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

C:\Users\smc\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [14]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.get_weights()

[array([[-0.39474368, -0.06055593],
        [ 0.4355086 ,  0.68928134]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6697852 ],
        [ 0.21313727]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
from sklearn.metrics import accuracy_score

In [18]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer ,metrics=['accuracy'])

In [20]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values, epochs=80, verbose=1, batch_size=1,validation_split=0.2)

Epoch 1/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 193ms/step - accuracy: 0.2917 - loss: 0.7451 - val_accuracy: 1.0000 - val_loss: 0.5025
Epoch 2/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.1667 - loss: 0.7743 - val_accuracy: 1.0000 - val_loss: 0.5049
Epoch 3/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.2917 - loss: 0.7395 - val_accuracy: 1.0000 - val_loss: 0.5066
Epoch 4/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.2917 - loss: 0.7372 - val_accuracy: 1.0000 - val_loss: 0.5083
Epoch 5/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5417 - loss: 0.6506 - val_accuracy: 1.0000 - val_loss: 0.5098
Epoch 6/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5417 - loss: 0.6499 - val_accuracy: 1.0000 - val_loss: 0.5115
Epoch 7/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.1667 - loss: 0.7582 - val_accuracy: 1.0000 - val_loss: 0.5136
Epoch 8/80
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.2917 - loss: 0.7279 - val_accuracy: 1.0000 - val_loss: 0.5155

In [21]:
model.get_weights()

[array([[-0.5105107 ,  0.04651537],
        [ 0.34738278,  0.79152673]], dtype=float32),
 array([-0.10100999,  0.10465448], dtype=float32),
 array([[-0.6399237 ],
        [ 0.29969263]], dtype=float32),
 array([0.08663186], dtype=float32)]